name: Mirror to GitLab and Hugging Face

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab Mirror
        run: |
          git push --prune https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/PrjSolutions/LabelOne-BuilderOne-Industrial-Suite.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*

      - name: Push to Hugging Face Mirror
        run: |
          git push --prune https://PrjSolutions:${{ secrets.HF_TOKEN }}@huggingface.co/datasets/PrjSolutions/LabelOne-BuilderOne-Industrial-Suite +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
